apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: phoenix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phoenix
        app.kubernetes.io/component: observability
    spec:
      containers:
        - name: phoenix
          image: arizephoenix/phoenix:version-11.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PHOENIX_PORT
              value: "6006"
            - name: PHOENIX_WORKING_DIR
              value: /tmp/phoenix
          ports:
            - name: http
              containerPort: 6006
          livenessProbe:
            tcpSocket:
              port: 6006
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6006
            initialDelaySeconds: 5
            periodSeconds: 5
