apiVersion: v1
kind: Secret
metadata:
  name: that-agent-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHAT_ID: "" # Optional, agent can self edit the allowed chats
